using System.Buffers.Binary;
using EgoistBattery.Core;

var checks = 0;
void Check(bool condition, string name) { checks++; if (!condition) throw new InvalidOperationException(name); }
for (byte raw = 0; raw <= 10; raw++)
{
    var reading = PlayStationParser.ParseDualSenseStatus(raw, "test");
    Check(reading.Minimum == raw * 10 && reading.Maximum == Math.Min(raw * 10 + 9, 100), $"DualSense интервал {raw}");
    Check(reading.State == ChargeState.Discharging, "Разрядка");
    var charging = PlayStationParser.ParseDualSenseStatus((byte)(raw | 0x10), "test");
    Check(charging.Minimum == reading.Minimum && charging.State == ChargeState.Charging, "USB не означает 100%");
}
Check(PlayStationParser.ParseDualSenseStatus(0x20, "test").Label == "100%", "Завершение зарядки");
foreach (byte bad in new byte[] { 0xA7, 0xB9, 0xF1 }) Check(PlayStationParser.ParseDualSenseStatus(bad, "test").State == ChargeState.Error && !PlayStationParser.ParseDualSenseStatus(bad, "test").HasLevel, "Ошибку нельзя выдавать за заряд");
Check(!PlayStationParser.ParseDualSenseStatus(0x0F, "test").HasLevel, "Неизвестная ёмкость");
Check(!PlayStationParser.ParseDualSenseStatus(0x37, "test").HasLevel, "Неизвестное состояние");
var usb = new byte[64]; usb[0] = 1; usb[53] = 0x17;
Check(PlayStationParser.Parse(usb, false, true).Label == "70–79%", "USB смещение батареи");
Check(!PlayStationParser.Parse(usb, true, true).HasLevel, "BT report 01 не содержит батареи даже при длине64");
Check(!PlayStationParser.Parse(usb.AsSpan(0, 54), false, true).HasLevel, "Обрезанный USB");
Check(!PlayStationParser.Parse([], false, true).HasLevel, "Пустой отчёт");
var bt = new byte[78]; bt[0] = 0x31; bt[54] = 0x18; bt[55] = 0x02;
BinaryPrimitives.WriteUInt32LittleEndian(bt.AsSpan(74), PlayStationParser.BluetoothCrc(bt.AsSpan(0, 74)));
Check(PlayStationParser.Parse(bt, true, true).Label == "80–89%", "BT смещение54 вместо55");
bt[8] ^= 1;
Check(!PlayStationParser.Parse(bt, true, true).HasLevel, "Повреждённый CRC");
Check(!BatteryReading.Percentage(101, "test", ReadingQuality.WindowsCache).HasLevel, "Windows 101 = неизвестно");
Check(BatteryReading.Percentage(0, "test", ReadingQuality.Live).HasLevel, "Нулевой заряд валиден");
Check(!BatteryReading.Percentage(-1, "test", ReadingQuality.Live).HasLevel, "Отрицательный процент");
var low = PlayStationParser.ParseDualSenseStatus(0x01, "test");
Check(low.IsLow(20), "Предупреждение по верхней границе");
Check(!PlayStationParser.ParseDualSenseStatus(0x02, "test").IsLow(20), "20–29 ещё не целиком ниже20");
Check(!PlayStationParser.ParseDualSenseStatus(0x11, "test").IsLow(20), "Заряжающийся контроллер без уведомления");
var stale = BatteryReading.Percentage(90, "Windows", ReadingQuality.WindowsCache);
var merged = SnapshotMerger.Merge([new("a", "DualSense", "Контроллер", "USB", true, low, "container"), new("b", "DualSense", "Контроллер", "Bluetooth", true, stale, "container")]);
Check(merged.Count == 1 && merged[0].Reading == low && merged[0].Transport.Contains(" + "), "Живое HID выше кеша Windows");
var distinct = SnapshotMerger.Merge([new("1", "DualSense", "Контроллер", "USB", true, low, "a"), new("2", "DualSense", "Контроллер", "USB", true, low, "b")]);
Check(distinct.Count == 2, "Одинаковые имена не объединяются");
var mouse = new DeviceSnapshot("mouse", "G304", "Мышь", "LIGHTSPEED", true, LogitechParser.Parse([90, 50, 0], 0x1000));
Check(mouse.Reading.Label == "90%", "Процент HID++ 1000");
Check(LogitechParser.Parse([34, 4, 1], 0x1004).State == ChargeState.Charging, "Состояние HID++ 1004");
var coarse = LogitechParser.Parse([0, 2, 0], 0x1004);
Check(coarse.Label == "Низкий" && coarse.HasData && !coarse.HasLevel, "Категория не подменяется вымышленным процентом");
Check(!LogitechParser.Parse([0, 80, 0], 0x1000).HasData, "HID++0 неизвестен, а не разряжен");
Check(!LogitechParser.Parse([200, 4, 0], 0x1004).HasData, "HID++ недопустимый процент");
Check(LogitechParser.Parse([90, 0, 5], 0x1000).State == ChargeState.Error, "Ошибка батареи HID++");
Check(!LogitechParser.Parse([90], 0x1000).HasLevel, "Обрезанный HID++");
Check(LogitechParser.IsResponse([0x11, 1, 3, 0x19, 90, 8, 0], 1, 3, 0x19), "Соответствующий ответ HID++");
Check(!LogitechParser.IsResponse([0x11, 1, 3, 0x18, 90, 8, 0], 1, 3, 0x19), "Чужой softwareId HID++");
Check(!LogitechParser.IsResponse([0x11, 2, 3, 0x19, 90, 8, 0], 1, 3, 0x19), "Чужой слот HID++");
Check(TrayPolicy.VisibleDevices([mouse]).Count == 1, "Подключённая мышь получает значок");
Check(TrayPolicy.VisibleDevices([mouse with { Connected = false }]).Count == 0, "Отключённая мышь теряет значок");
Check(TrayPolicy.VisibleDevices([mouse], ["mouse"]).Count == 0, "Скрытие отдельного значка");
Check(TrayPolicy.VisibleDevices([mouse, mouse with { Id = "mouse2" }]).Count == 2, "Два устройства получают два значка");
Check(TrayPolicy.VisibleDevices([mouse with { Kind = "Приёмник", Reading = BatteryReading.Missing("USB", "Батарея не объявлена") }]).Count == 0, "Приёмник не выдаётся за включённую мышь");
var bridged = SnapshotMerger.Merge([new("pnp", "Headset HFP", "Устройство", "Bluetooth", false, stale, "container"), new("bt", "Headset", "Наушники", "Bluetooth", true, BatteryReading.Missing("Windows", "Нет поля"), "container", "ABC")]);
Check(bridged.Count == 1 && bridged[0].Connected && bridged[0].Reading == stale && bridged[0].Name == "Headset", "Кеш PnP объединяется с реальным состоянием Bluetooth");
Check(bridged[0].Id == "identity:ABC", "Стабильный идентификатор значка независимо от источника");
// Показ: тон, порядок, группы и деления шкалы общие для окна и панели трея.
Check(DevicePresentation.ToneOf(mouse.Reading) == BatteryTone.Normal, "90% — обычный тон");
Check(DevicePresentation.ToneOf(BatteryReading.Percentage(18, "t", ReadingQuality.Live, ChargeState.Discharging)) == BatteryTone.Low, "18% — низкий");
Check(DevicePresentation.ToneOf(BatteryReading.Percentage(8, "t", ReadingQuality.Live, ChargeState.Discharging)) == BatteryTone.Critical, "8% — критический");
Check(DevicePresentation.ToneOf(BatteryReading.Percentage(8, "t", ReadingQuality.Live, ChargeState.Charging)) == BatteryTone.Charging, "Зарядка важнее низкого уровня");
Check(DevicePresentation.ToneOf(PlayStationParser.ParseDualSenseStatus(0xA7, "t")) == BatteryTone.Error, "Ошибка — отдельный тон");
Check(DevicePresentation.ToneOf(BatteryReading.Missing("t", "r")) == BatteryTone.Unknown, "Нет данных — неизвестный тон");
Check(DevicePresentation.ToneOf(coarse) == BatteryTone.Low, "Категория «Низкий» даёт низкий тон");
Check(DevicePresentation.ToneOf(BatteryReading.Percentage(30, "t", ReadingQuality.Live, ChargeState.Discharging), 40) == BatteryTone.Low, "Порог берётся из настроек");
Check(DevicePresentation.Cells(mouse.Reading) == (27, 0), "90% = 27 из 30 делений");
Check(DevicePresentation.Cells(BatteryReading.Percentage(100, "t", ReadingQuality.Live)) == (30, 0), "100% = все деления");
Check(DevicePresentation.Cells(BatteryReading.Percentage(0, "t", ReadingQuality.Live)) == (0, 0), "0% = пустая шкала");
Check(DevicePresentation.Cells(BatteryReading.Percentage(2, "t", ReadingQuality.Live)) == (1, 0), "Малый заряд виден хотя бы одним делением");
var interval = PlayStationParser.ParseDualSenseStatus(0x01, "t");
Check(DevicePresentation.Cells(interval) == (3, 3), "Интервал 10–19% — сплошные деления и штриховка");
Check(DevicePresentation.CellCount(coarse) == 4 && DevicePresentation.Cells(coarse) == (2, 0) && DevicePresentation.CellCount(mouse.Reading) == 30, "Категория рисуется четырьмя ступенями, а не процентом");
Check(DevicePresentation.TrayValue(interval) == "10+" && DevicePresentation.TrayValue(mouse.Reading) == "90" && DevicePresentation.TrayValue(coarse) == "?", "Текст значка трея");
var silentDevice = new DeviceSnapshot("kb", "Impact 80", "Клавиатура", "USB", true, BatteryReading.Missing("USB", "нет"));
var offlineDevice = new DeviceSnapshot("hp", "Наушники", "Наушники", "Bluetooth", false, stale);
var lowDevice = new DeviceSnapshot("ds", "DualSense", "Контроллер", "Bluetooth", true, interval);
var ordered = DevicePresentation.Order([offlineDevice, silentDevice, mouse, lowDevice]);
Check(ordered.Select(x => x.Id).SequenceEqual(["ds", "mouse", "kb", "hp"]), "Порядок: меньше заряда выше, затем без данных, затем отключённые");
Check(DevicePresentation.GroupOf(silentDevice) == DeviceGroup.Silent && DevicePresentation.GroupOf(offlineDevice) == DeviceGroup.Offline && DevicePresentation.GroupOf(mouse) == DeviceGroup.Measured, "Группы устройств");
var spectrumLow = BatterySpectrum.At(0); var spectrumFull = BatterySpectrum.At(1); var spectrumMid = BatterySpectrum.At(0.5);
Check(spectrumLow == ((byte)255, (byte)90, (byte)79) && spectrumFull == ((byte)198, (byte)242, (byte)78) && spectrumMid == ((byte)246, (byte)216, (byte)74), "Спектр: красный, жёлтый, лайм");
Check(BatterySpectrum.At(-3) == spectrumLow && BatterySpectrum.At(9) == spectrumFull, "Спектр ограничен краями");
var spectrumQuarter = BatterySpectrum.At(0.125); Check(spectrumQuarter.R == 255 && spectrumQuarter.G > 90 && spectrumQuarter.G < 165, "Спектр плавный между красным и оранжевым");
Check(BatterySpectrum.LevelOf(interval) is { } mid && Math.Abs(mid - 0.14) < 0.001 && BatterySpectrum.LevelOf(coarse) == 0.375 && BatterySpectrum.LevelOf(BatteryReading.Missing("t", "r")) is null, "Доля для окраски");
var dualSense = new DeviceSnapshot("ds", "DualSense Wireless Controller", "Контроллер", "Bluetooth", true, BatteryReading.Percentage(95, "t", ReadingQuality.Live));
var lowMouse = new DeviceSnapshot("m", "Мышь", "Мышь", "USB", true, BatteryReading.Percentage(10, "t", ReadingQuality.Live));
Check(TrayPolicy.IconDevice([lowMouse, dualSense])?.Id == "ds", "Значок трея: приоритет DualSense");
Check(TrayPolicy.IconDevice([lowMouse, dualSense], "m")?.Id == "m", "Значок трея: закреплённое устройство");
Check(TrayPolicy.IconDevice([lowMouse, dualSense with { Connected = false }])?.Id == "m", "Значок трея: отключённый DualSense не выбирается");
Check(TrayPolicy.IconDevice([lowMouse, mouse])?.Id == "m", "Значок трея: без DualSense — наименьший заряд");
Check(TrayPolicy.IconDevice([]) is null, "Значок трея: нет устройств");
Console.WriteLine($"PASS: {checks} проверок протокола, точности и объединения устройств.");
